feat(): cloudDocument event
MyUnisoft/events pull request #166
Opened 2023-12-18 13:18 UTC by Rossb0b

2023-12-18 15:24 UTC, PierreDemailly approved these changes

2023-12-19 07:07 UTC, Dafyh approved these changes

2023-12-19 09:21 UTC, fraxken requested changes

2023-12-19 09:21 UTC, fraxken commented on src/types/events.ts
> +    reason: string;
optionel, présent uniquement si status est égal rejected

2023-12-19 12:20 UTC, fraxken approved these changes

2023-12-19 12:22 UTC, PierreDemailly approved these changes

2023-12-19 12:38 UTC, Dafyh approved these changes

2023-12-19 12:40 UTC, merged