refacto(): Incomer name & prefix as readonly, abortSignal on incomer init
MyUnisoft/events pull request #34
Opened 2023-06-20 15:10 UTC by Rossb0b

2023-06-20 15:18 UTC, PierreDemailly approved these changes

2023-06-20 15:18 UTC, PierreDemailly commented on test/UT/class/eventManagement/incomer.spec.ts
> +import timers from "timers/promises";
```suggestion
import timers from "node:timers/promises";
```

2023-06-21 15:20 UTC, fraxken requested changes

2023-06-22 00:20 UTC, fraxken approved these changes

2023-06-22 11:55 UTC, merged