Fix open handles & possibility to set the logLevel
MyUnisoft/events pull request #40
Opened 2023-06-29 13:41 UTC by Rossb0b

2023-06-29 13:48 UTC, PierreDemailly approved these changes

2023-07-04 12:02 UTC, Dafyh commented on src/utils/index.ts
> +  })].join("");
Un peu galère ce map avec les conditions ? Peu être faire un générator + join("|") ?
```ts
function* mapped() {
    for (const [ key, value] of Object.entries(message[kCustomKey])) {
      const formattedKey = kScopeKeys[key]

      if (!formattedKey) {
        continue;
      }

      yield `${formattedKey}:${value}`
    }
  }
  const logs = Array.from(mapped()).join("|")
```

2023-07-04 18:09 UTC, fraxken requested changes

2023-07-04 18:09 UTC, fraxken commented on src/utils/index.ts
> +export function defaultStandardLog(data: Record<string, any>, message: string) {
pourquoi Record? Le type c'est Event plutôt non?

2023-07-04 18:09 UTC, fraxken commented on src/utils/index.ts
> +  const formattedMessage = `${JSON.stringify(data)}, ${message}`;
Pour moi le JSON.stringify(data) n'est pas voulu/nécessaire

2023-07-05 10:15 UTC, Rossb0b commented on src/utils/index.ts
> +  const formattedMessage = `${JSON.stringify(data)}, ${message}`;
C'est voulu, sinon il print `[Object, Object]`, en utilisant le transport, il clean up la string et évite d'avoir les back slashs et les doubles quotes*

2023-07-05 10:18 UTC, Rossb0b commented on src/utils/index.ts
> +export function defaultStandardLog(data: Record<string, any>, message: string) {
Je log aussi les events "internes" et dans le cas où un event est back-up, il faudrait que j'identifie l'event en tant qu'event custom pour forcer le type et utiliser le standardLog même si on est bien d'accord, qu'en dehors d'un event custom, la function ne fait rien de plus que renvoyer les inputs

2023-07-05 19:01 UTC, fraxken commented on src/utils/index.ts
> +  const formattedMessage = `${JSON.stringify(data)}, ${message}`;
Tu m'as pas compris, je veux pas avoir l'objet dans la log.

2023-07-07 10:06 UTC, fraxken approved these changes

2023-07-07 10:59 UTC, Dafyh approved these changes

2023-07-07 13:58 UTC, merged