Refacto around naming, exports & documentation
MyUnisoft/events pull request #9
Opened 2022-08-26 00:48 UTC by Rossb0b

2022-08-26 08:23 UTC, fraxken requested changes

2022-08-26 08:23 UTC, fraxken commented on example/fastify/feature/webhook.ts
> +import { FastifyInstance } from "fastify/types/instance";
Possible en un seul import non ?

2022-08-26 08:23 UTC, fraxken commented on example/fastify/index.ts
> +});
J'aurais personnellement fait un seul fichier app pour simplifier l'exemple.

2022-08-30 19:05 UTC, fraxken requested changes

2022-08-30 19:05 UTC, fraxken commented on README.md
> +```
Pas forcément nécessaire d'avoir l'exemple ici (simplement pointer la présence d'un exemple dans le dossier example suffit).

2022-08-30 19:05 UTC, fraxken commented on README.md
> +};
Pourquoi faire un cas d'usage avec l'évènement complet plutôt que de faire un évènement complet dans le premier cas d'usage ?

2022-08-30 19:05 UTC, fraxken commented on README.md
> +- Specifying valide Events registring an endpoint related to Webhooks.
C'est moche de faire des listes de un élément (Pour séparer des exemples j'utiliserai plutôt une ligne).

2022-09-02 09:17 UTC, fraxken approved these changes
LGTM

2022-09-02 15:14 UTC, Dafyh commented on example/fastify/app.ts
> +export function buildServer(opts = {}): FastifyInstance {
Comme ce n'est pas utilisé
```suggestion
export function buildServer(): FastifyInstance {
```

2022-09-02 15:14 UTC, Dafyh commented on example/fastify/app.ts
> +});
idem
```suggestion
const server = buildServer();
```

2022-09-05 11:43 UTC, Dafyh approved these changes

2022-09-05 15:04 UTC, merged